### ISSUE TITLE
Chat whispers don't work correctly  

### ISSUE THREAD

**Issue by CodingTwist** [DaMarine/Slabserver-Bugs#71]
When using /msg the sender won't see the sent message but the receiver does. _(also the ding doesn't work)_
My side:
![image](https://github.com/user-attachments/assets/3dd35ba9-93d3-4991-a98b-690a373e5170)
![image](https://github.com/user-attachments/assets/8c30bb1e-3e16-44ae-85e0-a278a1506890)

Alex's side: 
![image](https://github.com/user-attachments/assets/bf58a8ee-276f-483c-9601-c4731427dbe8)

**Comment by DaMarine** [comment]
Were they in the RW at the time?

**Comment by CodingTwist** [comment]
Nope both players were in the main world

**Comment by chrissamael** [comment]
Does it also occur with `/w`?

Checking the logs, I'm pretty sure it would: ```
[11:32:51] [Server thread/WARN]: [VentureChat] Plugin VentureChat v3.7.1 generated an exception whilst handling plugin message
java.lang.BootstrapMethodError: bootstrap method initialization exception
	at VentureChat-3.7.1.jar/mineverse.Aust1n46.chat.utilities.Format.getSound(Format.java:970) ~[VentureChat-3.7.1.jar:?]
	at VentureChat-3.7.1.jar/mineverse.Aust1n46.chat.utilities.Format.playMessageSound(Format.java:964) ~[VentureChat-3.7.1.jar:?]
	at VentureChat-3.7.1.jar/mineverse.Aust1n46.chat.MineverseChat.onPluginMessageReceived(MineverseChat.java:1018) ~[VentureChat-3.7.1.jar:?]
	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleCustomPayload(ServerCommonPacketListenerImpl.java:185) ~[paper-1.21.4.jar:1.21.4-37-946314f]
	at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:28) ~[paper-1.21.4.jar:1.21.4-37-946314f]
	at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:13) ~[paper-1.21.4.jar:1.21.4-37-946314f]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:29) ~[paper-1.21.4.jar:1.21.4-37-946314f]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-37-946314f]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[paper-1.21.4.jar:1.21.4-37-946314f]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-37-946314f]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1448) ~[paper-1.21.4.jar:1.21.4-37-946314f]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176) ~[paper-1.21.4.jar:1.21.4-37-946314f]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[paper-1.21.4.jar:1.21.4-37-946314f]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[paper-1.21.4.jar:1.21.4-37-946314f]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1422) ~[paper-1.21.4.jar:1.21.4-37-946314f]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139) ~[paper-1.21.4.jar:1.21.4-37-946314f]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1379) ~[paper-1.21.4.jar:1.21.4-37-946314f]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1387) ~[paper-1.21.4.jar:1.21.4-37-946314f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.21.4.jar:1.21.4-37-946314f]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-37-946314f]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]```

**Comment by chrissamael** [comment]
Seems we are [not the only ones](https://www.spigotmc.org/threads/venturechat.24005/page-557#post-4807315) experiencing this issue currently :/

**Comment by chrissamael** [comment]
I have, for the time being, disabled the sound, which fixes the current issue

Will have to wait for VentureChat to fix whatever went wrong with the sound due to the update

**Comment by DaMarine** [comment]
Doing some general cleanup around our issues, as of Jan 24th 2025 the VentureChat dev is finally looking into the issue on their end:

https://www.spigotmc.org/threads/venturechat.24005/page-557#post-4820726

Our fix will likely remain in place for the foreseeable future, this is very low priority for us to keep tabs on.

**Comment by DaMarine** [comment]
Fixed by VentureChat
